<?php
class Config
{
	const MIN_PHP_VERSION = "5.4.4";
	const WEBSITE_VERSION = "1.0.0";
	const CHARSET = "utf-8";
	const MAIN_CLASS = "home";
	const MAIN_METHOD = "index";  
	const MAIN_LANG = "ge";
	const DIR = "/home/mscge63/public_html/";
	const CACHE = "/home/mscge63/public_html/public/_cache/";
	const WEBSITE = "https://msc.ge/";
	const WEBSITE_ = "https://msc.ge";
	const ADMIN_DASHBOARD = "/dashboard/index";
	const ADMIN_DASHBOARD_COMMENTS = "https://msc.ge/ge/dashboard/comments";
	const PUBLIC_FOLDER = "https://msc.ge/public/";
	const PUBLIC_FOLDER_NAME = "public";
	const AUTHER = "Giorgi Gvazava";
	const PAGE_PREFIX = "page";
	const NAME = "Marneuli";
	const DESC = "Marneuli";
	const KEYWORDS = "Marneuli";
	const DB_HOST = "localhost";
	const DB = "mscge63_mar";
	const DB_USER = "mscge63_mar";
	const DB_PASS = "~xU,oy}j[wEG";
	const SESSION_PREFIX = "marneuli2_";
	const ADMIN_USER = "admin";
	const ADMIN_PASS = "123";
	const RECIEVER_EMAIL = "giorgigvazava87@gmail.com"; 
	const EMAIL_HOST = "msc.ge";
	const EMAIL_NAME = "MSC";
	const EMAIL_USERNAME = "info@msc.ge";
	const EMAIL_PASSWORD = "\$NGLSR!G8{C,";
	const EMAIL_SUBJECT = "";
	const EMAIL_TO_NAME = "";
	const EMAIL_TO = "";	
	const PAYPAL_CLIENT_SENDBOX = "";	
	const PAYPAL_SECRET_SENDBOX = "";
	const PAYPAL_CLIENT = "";
	const PAYPAL_SECRET = "";
	const RESTRICTED_SLUGS = "ajax|dashboard|image|manager|protect|payments|closeday";
	const RESTRICTED_MODULE_DELETE_IDX = "181|150|151|152|153|154|155"; // 3|4|5|49
	const RESTRICTED_MODULE_IDX = "9"; // IF NOT ROOT
	const DEFAULT_MODULE = "contactdata";	
	const NEWS_PER_PAGE = 5;	
	const STAFF_PER_PAGE = 10;	
	const HOME_PAGE_NEWS_NUM = 3;	
	const HOME_PAGE_STAFF_NUM = 2;	
	const HOME_PAGE_VACANCIES_NUM = 3;	
	const HOME_PAGE_GALLERY_NUM = 14;	
	const HOME_PAGE_PARTNERS_NUM = 10;	
	const VACANCIES_PER_PAGE = 10;	
	const LEFTSIDE_NEWS_NUM = 3;	
	const FOOTER_NEWS_NUM = 5;	
	const FOOTER_USEFULL_LINKS_NUM = 5;	
	const FOOTER_WORKING_HOURS_NUM = 7;	
	const GOOGLE_API_KEY = "AIzaSyBmWx971ahvSKhe2MHPmXoZ_Q2xeTtLqjY";	

	const LANG_ARRAY = "en|ge"; //|en|ru
}